### PR TITLE
Fix the type of model_objs in bulk_upsert

### PR DESCRIPTION
**Pull request by alextatarinov**
This is probably not worth a release, but the wrong types make PyCharm (and me) sad. 
Otherwise, great package, thanks!

### CODE REVIEW

**Comment by wesokes** [comment]
looks like this code is now in the repository, i'll go ahead and close this. thanks!

**Comment by alextatarinov** [comment]
Are you sure? Both master and develop have the old version and the file was modified 2 years ago.

**Comment by wesokes** [comment]
@alextatarinov sorry about that, i must have been looking at a different line. i'll get this updated and bumped

**Comment by wesokes** [comment]
@alextatarinov the new version (2.0.1) is published on pypi

**Comment by alextatarinov** [comment]
Great, thanks!

**Pull request merged**
