### PR TITLE
Allow native sync

### PR DESCRIPTION
**Pull request by wesleykendall**
@wesokes @jaredlewis this updates the `sync` function to take a `native` parameter. When `native` is provided, it will do the native bulk upsert and then delete anything that was not in the returned results.

I added a test package called `parameterize` to parameterize the sync tests so they do a native and non native sync. pytest has this functionality by default if you find it useful and want to update the test runner one day.

I believe this handles all scenarios, and all of the old tests pass. Any comments?

### CODE REVIEW

**Comment by travistruett** [comment]
Is this quine complete, by chance?
https://en.wikipedia.org/wiki/Quine_(computing)

**Comment by jaredlewis** [comment]
hes back

**Comment by wesleykendall** [comment]
@travistruett no quine completion yet, but I'll add it as an issue and assign it to @robdmc

**Comment by jaredlewis** [comment]
This is awesome, thanks @wesleykendall really like that parameterize package. I'll merge this and do a release

**Comment by jaredlewis** [comment]
@wesleykendall pushed as 0.13.1

**Pull request merged**
